### ISSUE TITLE
Tester doesn't work with paths contain spaces

### ISSUE THREAD

**Issue by ohld** [annamel/acroparallels2016#18]
Dear @aglab2,
I have a HD with the name "OHLD MAC HD" that contains spaces. And then I try to start tester from this HD is drops: 
> ls: /Volumes/OHLD: No such file or directory
> ls: HD/Documents/Developer/parallels/acroparallels2016/tester/..//**: No such file or directory
> ls: MAC: No such file or directory

Full path to repository: 
> /Volumes/OHLD\ MAC\ HD/Documents/Developer/parallels/acroparallels2016/

Full output: 
![2016-04-22 15 16 05](https://cloud.githubusercontent.com/assets/5613295/14741452/4de4af04-08a7-11e6-92f8-e31865f60b51.png)

**Comment by aglab2** [comment]
Made fixes for wrong mktemp behaviour

**Comment by ohld** [comment]
Still: 

> MacBook-Pro-Daniil:tester daniilokhlopkov$ ROOT_LIB_DIR="../dokhlopkov" ./tester.sh
> /tmp/tmp.TklmoRfrc4
> ls: /Volumes/OHLD: No such file or directory
> ls: HD/Documents/Developer/parallels/acroparallels2016/tester/..//**: No such file or directory
> ls: MAC: No such file or directory
> 
> ./tester.sh: line 108: /Volumes/OHLD: No such file or directory

**Comment by aglab2** [comment]
Hello @ohld! I have reworked tester.sh so whitespace symbols are supported. Please check. Thank you!

**Comment by ohld** [comment]
I checked you're correction and now there is that error: 
```
MacBook-Pro-Daniil:tester daniilokhlopkov$ ROOT_LIB_DIR="../dokhlopkov" ./tester.sh
/tmp/tmp.q5Pqtg1Rjd
ls: fts_open: No such file or directory
./tester.sh: line 58: [: too many arguments
./tester.sh: line 122: /Volum: No such file or directory
./tester.sh: line 126: pushd: ../dokhlopkov/mapp: No such file or directory
./tester.sh: line 129: popd: directory stack empty
```

**Comment by ohld** [comment]
I checked all your updates and now it seems to ignore all the words after space in path.
Look at the whole output:
```
MacBook-Pro-Daniil:tester daniilokhlopkov$ ROOT_LIB_DIR="../dokhlopkov" ./tester.sh
/tmp/tmp.b144mNrGqu
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineSystem.cmake:177 (file):
  file failed to open for writing (No such file or directory):

    /Volumes/**OHLD**/CMakeFiles/CMakeOutput.log
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: Could not open file for write in copy operation /Volumes/**OHLD**/CMakeFiles/3.5.1/CMakeSystem.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineSystem.cmake:189 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:141 (file):
  file problem creating directory: /Volumes/**OHLD**/CMakeFiles/3.5.1/CompilerIdC
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:40 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCCompiler.cmake:118 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:141 (file):
  file problem creating directory: /Volumes/OHLD/CMakeFiles/3.5.1/CompilerIdC
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:40 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCCompiler.cmake:118 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:141 (file):
  file problem creating directory: /Volumes/OHLD/CMakeFiles/3.5.1/CompilerIdC
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:40 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCCompiler.cmake:118 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:647 (file):
  file failed to open for writing (No such file or directory):

    /Volumes/OHLD/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:55 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCCompiler.cmake:118 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


CMake Error: Could not open file for write in copy operation /Volumes/OHLD/CMakeFiles/3.5.1/CMakeCCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCCompiler.cmake:181 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: Could not find cmake module file: /Volumes/OHLD/CMakeFiles/3.5.1/CMakeCCompiler.cmake
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:141 (file):
  file problem creating directory:
  /Volumes/OHLD/CMakeFiles/3.5.1/CompilerIdCXX
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:40 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:113 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:141 (file):
  file problem creating directory:
  /Volumes/OHLD/CMakeFiles/3.5.1/CompilerIdCXX
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:40 (CMAKE_DETERMINE_COMPILER_ID_BUILD)
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:113 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:647 (file):
  file failed to open for writing (No such file or directory):

    /Volumes/OHLD/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCompilerId.cmake:55 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)
  /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:113 (CMAKE_DETERMINE_COMPILER_ID)
  CMakeLists.txt:2 (project)


CMake Error: Could not open file for write in copy operation /Volumes/OHLD/CMakeFiles/3.5.1/CMakeCXXCompiler.cmake.tmp
CMake Error: : System Error: No such file or directory
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeDetermineCXXCompiler.cmake:179 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: Could not find cmake module file: /Volumes/**OHLD**/CMakeFiles/3.5.1/CMakeCXXCompiler.cmake
CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeTestCCompiler.cmake:35 (file):
  file failed to open for writing (No such file or directory):

    /Volumes/**OHLD**/CMakeFiles/CMakeTmp/testCCompiler.c
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeTestCCompiler.cmake:47 (try_compile):
  Unknown extension ".c" for file

    /Volumes/OHLD/CMakeFiles/CMakeTmp/testCCompiler.c

  try_compile() works only for enabled languages.  Currently these are:

    C CXX

  See project() command to enable other languages.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeTestCCompiler.cmake:58 (file):
  file failed to open for writing (No such file or directory):

    /Volumes/**OHLD**/CMakeFiles/CMakeError.log
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error at /usr/local/Cellar/cmake/3.5.1/share/cmake/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler
  "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"
  is not able to compile a simple test program.

  It fails with the following output:

   

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: Cannot open file for write: /Volumes/**OHLD**/CMakeCache.txt.tmp
CMake Error: : System Error: Permission denied
CMake Error: Unable to open cache file for save. /Volumes/**OHLD**/CMakeCache.txt
CMake Error: : System Error: Permission denied
=========================================================
Tests:    0 | Passed:   0 | Failed:   0

```

**Comment by aglab2** [comment]
Hello @ohld! I was not able to recreate your usecase because if I try to build your project with
`cmake .
make`
by myself I get build errors. Could you fix them so I can investigate your issue. I include build errors. Thank you. 
`In file included from /home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/chunks.c:7:0:
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/hashtable/hashtable.h:21:9: error: unknown type name ‘uint32_t’
         uint32_t count;
         ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/hashtable/hashtable.h:22:9: error: unknown type name ‘uint32_t’
         uint32_t size;
         ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/hashtable/hashtable.h:26:35: error: unknown type name ‘uint32_t’
 hashtable_t *hashtable_construct (uint32_t size);
                                   ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/hashtable/hashtable.h:27:1: error: unknown type name ‘uint32_t’
 uint32_t hashtable_destruct (hashtable_t *hashtable);
 ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/hashtable/hashtable.h:29:1: error: unknown type name ‘uint32_t’
 uint32_t hashtable_count (hashtable_t *hashtable);
 ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/hashtable/hashtable.h:30:1: error: unknown type name ‘uint32_t’
 uint32_t hashtable_size (hashtable_t *hashtable);
 ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/hashtable/hashtable.h:32:1: error: unknown type name ‘uint32_t’
 uint32_t hashtable_add (hashtable_t *hashtable, hkey_t key, hval_t value);
 ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/hashtable/hashtable.h:34:1: error: unknown type name ‘uint32_t’
 uint32_t hashtable_delete (hashtable_t *hashtable, hkey_t key);
 ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/chunks.c: In function ‘cpool_init’:
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/chunks.c:214:16: warning: implicit declaration of function ‘hashtable_construct’ [-Wimplicit-function-declaration]
    cpool->ht = hashtable_construct(HTBL_SIZE);
                ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/chunks.c:214:14: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    cpool->ht = hashtable_construct(HTBL_SIZE);
              ^
/home/aglab2/Documents/acroparallels2016/dokhlopkov/mapped_file/sources/chunks.c:215:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
    cpool->mem_ht = hashtable_construct(HTBL_SIZE);
                  ^
CMakeFiles/mappedfile.dir/build.make:86: recipe for target 'CMakeFiles/mappedfile.dir/sources/chunks.c.o' failed
make[2]: *** [CMakeFiles/mappedfile.dir/sources/chunks.c.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mappedfile.dir/all' failed
make[1]: *** [CMakeFiles/mappedfile.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by aglab2** [comment]
Hello @ohld. I have worked on your issue and found solution. Please try it. I recommend you to add stdint.h not to get build warnings.
